### ISSUE TITLE
sen2cor 2.5.5 errored with oldname SAFE

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#118]
Launching sen2cor on same oldname SAFE, an error occurs:
```r
sen2cor(c("L1C/S2A_OPER_PRD_MSIL1C_PDMC_20160702T015653_R065_V20160701T102057_20160701T102057.SAFE","L1C/S2A_OPER_PRD_MSIL1C_PDMC_20160621T190703_R065_V20160621T102024_20160621T102024.SAFE"))
```
```
Operation mode PDGS is not supported for Product version 13.1.
Operation mode will be reset to TOOLBOX.

Sentinel-2 Level 2A Processor (Sen2Cor). Version: 2.5.5, created: 2018.03.19, supporting Level-1C product version <= 14.5 started ...
Product version: 13.1. Operation mode: TOOLBOX. Processing baseline: 02.04.
 No resolution specified, will process all resolutions.
Process L2A_ProcessTile-1:
Traceback (most recent call last):
  File "/home/lranghetti/share/git/github/ranghetti/sen2r/inst/sen2cor/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lranghetti/share/git/github/ranghetti/sen2r/inst/sen2cor/lib/python2.7/site-packages/sen2cor/L2A_ProcessTile.py", line 122, in run
    if not self.process_60():
  File "/home/lranghetti/share/git/github/ranghetti/sen2r/inst/sen2cor/lib/python2.7/site-packages/sen2cor/L2A_ProcessTile.py", line 147, in process_60
    self.tables = L2A_Tables(self.config)
  File "/home/lranghetti/share/git/github/ranghetti/sen2r/inst/sen2cor/lib/python2.7/site-packages/sen2cor/L2A_Tables.py", line 251, in __init__
    indataset = glymur.Jp2k(L1C_Tile_PVI_File)
  File "/home/lranghetti/share/git/github/ranghetti/sen2r/inst/sen2cor/lib/python2.7/site-packages/glymur/jp2k.py", line 159, in __init__
    self.parse()
  File "/home/lranghetti/share/git/github/ranghetti/sen2r/inst/sen2cor/lib/python2.7/site-packages/glymur/jp2k.py", line 268, in parse
    self.length = os.path.getsize(self.filename)
  File "/home/lranghetti/share/git/github/ranghetti/sen2r/inst/sen2cor/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/tmp/RtmpNZZYzj/sen2cor_70cd199ab3d0/S2A_USER_PRD_MSIL2A_PDMC_20160621T190703_R065_V20160621T102024_20160621T102024.SAFE/GRANULE/S2A_USER_MSI_L2A_TL_SGS__20160621T172838_A005210_T32TMR_N02.04/QI_DATA/S2A_OPER_PVI_L1C_TL_SGS__20160621T172838_A0
```

This seems related to an issue in managing PVI preview files ([see](https://forum.step.esa.int/t/sen2cor-2-5-5-no-such-file--pvi-jp2/9461/11)).
Try to:
- patch sen2cor code in order to ignore PVI files; or
- change the sen2r structure in order to install both sen2cor 2.5.5 and 2.4.0, and to use sen2cor 2.4.0 for oldname products.

**Comment by ranghetti** [comment]
Oldname SAFEs are no longer supported.
