### ISSUE TITLE
Problem with processing raw SAFE files

### ISSUE THREAD

**Issue by Nowosad** [ranghetti/sen2r#371]
**Bug description**

I have been unable to process the raw SAFE files in both interactive and command-line mode (see the attached .json file - [onesen-safe.json.zip](https://github.com/ranghetti/sen2r/files/5830576/onesen-safe.json.zip)).
An error in the interactive mode occurs when I try to run the processing and looks as following:

![2021-01-18_14-53](https://user-images.githubusercontent.com/3457131/104927935-50329b80-59a2-11eb-9616-5572fecd7662.png)

The command-line mode error is shown below:

**Reproducible example**

```r
library(sen2r)
# install_sen2cor()
sen2r()

out_paths_3 = sen2r(
  param_list = "onesen-safe.json",
  path_subdirs = TRUE,
  thumbnails = TRUE
)
```

**Expected and actual behavior**

```
[2021-01-18 14:54:28] #### Starting sen2r execution. ####
[2021-01-18 14:54:29] Searching for available SAFE products on SciHub...
although coordinates are longitude/latitude, st_union assumes that they are planar
although coordinates are longitude/latitude, st_union assumes that they are planar
Error in unlist(s2names$exi[c("indices", "rgb", "masked", "warped_nomsk",  : 
  object 's2names' not found
...
```

**System information**

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 33 (Thirty Three)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libflexiblas.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.5.0 sen2r_1.4.0

loaded via a namespace (and not attached):
 [1] httr_1.4.2           shinyFiles_0.9.0     jsonlite_1.7.2       geojsonlint_0.4.0    foreach_1.5.1       
 [6] sp_1.4-5             yaml_2.2.1           pillar_1.4.7         lattice_0.20-41      glue_1.4.2          
[11] digest_0.6.27        promises_1.1.1       htmltools_0.5.1      httpuv_1.5.4         XML_3.99-0.5        
[16] pkgconfig_2.0.3      rmapshaper_0.4.4     httpcode_0.3.0       raster_3.4-5         stars_0.5-0         
[21] purrr_0.3.4          xtable_1.8-4         later_1.1.0.1        mapedit_0.6.0        tibble_3.0.4        
[26] generics_0.1.0       ellipsis_0.3.1       shinyjs_2.0.0        geojsonio_0.9.2      RcppTOML_0.1.7      
[31] lazyeval_0.2.2       magrittr_2.0.1       crayon_1.3.4         mime_0.9             evaluate_0.14       
[36] maptools_1.0-2       fs_1.5.0             doParallel_1.0.16    xml2_1.3.2           lwgeom_0.2-5        
[41] foreign_0.8-80       class_7.3-17         shinydashboard_0.7.1 tools_4.0.3          data.table_1.13.6   
[46] lifecycle_0.2.0      geojson_0.3.4        V8_3.4.0             compiler_4.0.3       e1071_1.7-4         
[51] jqr_1.2.0            rlang_0.4.10         classInt_0.4-3       units_0.6-7          grid_4.0.3          
[56] iterators_1.0.13     rstudioapi_0.13      htmlwidgets_1.5.3    crosstalk_1.1.1      rmarkdown_2.6       
[61] shinyWidgets_0.5.4   codetools_0.2-16     abind_1.4-5          DBI_1.1.1            jsonvalidate_1.1.0  
[66] curl_4.3             R6_2.5.0             knitr_1.30           dplyr_1.0.2          rgdal_1.5-19        
[71] fastmap_1.0.1        rgeos_0.5-5          KernSmooth_2.23-17   stringi_1.5.3        parallel_4.0.3      
[76] crul_1.0.0           Rcpp_1.0.6           vctrs_0.3.6          sf_0.9-8             xfun_0.20           
[81] leaflet_2.0.4.1      tidyselect_1.1.0     leafpm_0.1.0        
> packageVersion("sen2r")
[1] ‘1.4.0’
> sen2r::load_binpaths()
$sen2cor
[1] "/home/jn/.sen2r/sen2cor/bin/L2A_Process"

attr(,"path")
[1] "/home/jn/.sen2r/paths.json"
```

**Comment by ranghetti** [comment]
Issue should be fixed in the develop branch: please install it with `remotes::install_github("ranghetti/sen2r", ref = "devel")`, retry and let me know if all is ok.

If so I will merge it in master after having added a testthat test for this case (actually `sen2r(..., preprocess = FALSE)` is not being tested).

**Comment by Nowosad** [comment]
Hi Luigi @ranghetti, in short:

1. The command line error is fixed now.
2. The GUI error (see the screenshot in my first post) is still here.
3. The command line function runs indefinitely - it starts a python process for a few minutes, and then nothing happens); if you want I can create a new issue for this...

**Comment by ranghetti** [comment]
Sorry for waiting. Point 2 should be fixed (reinstall from develop branch). Regarding to 3, it could be a Sen2Cor error.

To check that:
1. verify that downloaded SAFE are valid:
    ```r
    path_l1c <- jsonlite::fromJSON("onesen-safe.json")$path_l1c
    path_l2a <- jsonlite::fromJSON("onesen-safe.json")$path_l2a
    safe_isvalid(list.files(path_l1c, "SAFE$", full.names = TRUE))
    ```
2. run `sen2cor()` with argument `kill_errored = TRUE` (this option is not implemented in `sen2r()`):
    ```r
    sen2cor(
      list.files(path_l1c, "SAFE$", full.names = TRUE),
      outdir = path_l2a,
      use_dem = TRUE,
      kill_errored = TRUE
    )
    ```

**Comment by Nowosad** [comment]
Thanks a lot @ranghetti! 
`sen2cor` works well with `use_dem = FALSE`, however, the calculation stops after a few minutes when `use_dem = TRUE`. This is probably the same issue as https://github.com/ranghetti/sen2r/issues/346.

**Comment by Nowosad** [comment]
Update:

The calculation stops after a few minutes when `use_dem = TRUE`. This is probably the same issue as https://github.com/ranghetti/sen2r/issues/346.

When `use_dem = TRUE`, the error is as following:

```
> safe_isvalid(c("sentinel/1c/S2A_MSIL1C_20170726T173121_N0205_R069_T12JXR_20170726T173124.SAFE",
+     "sentinel/1c/S2A_MSIL1C_20170726T173121_N0205_R069_T12JXQ_20170726T173124.SAFE"))
S2A_MSIL1C_20170726T173121_N0205_R069_T12JXR_20170726T173124.SAFE S2A_MSIL1C_20170726T173121_N0205_R069_T12JXQ_20170726T173124.SAFE 
                                                             TRUE                                                              TRUE 
```

```
> sen2cor(
+   c("sentinel/1c/S2A_MSIL1C_20170726T173121_N0205_R069_T12JXR_20170726T173124.SAFE",
+     "sentinel/1c/S2A_MSIL1C_20170726T173121_N0205_R069_T12JXQ_20170726T173124.SAFE"), 
+   outdir = tempdir(),
+   use_dem = FALSE,
+   kill_errored = TRUE
+ )
```

```
[2021-02-03 19:39:39] Launching Sen2Cor on
     S2A_MSIL1C_20170726T173121_N0205_R069_T12JXR_20170726T173124.SAFE
     (1/2)...
Operation mode PDGS is not supported for Product version 14.2.
Operation mode will be reset to TOOLBOX.

Sentinel-2 Level 2A Processor (Sen2Cor). Version: 2.5.5, created: 2018.03.19, supporting Level-1C product version <= 14.5 started ...
Product version: 14.2. Operation mode: TOOLBOX. Processing baseline: 02.05.
 No resolution specified, will process all resolutions.
Progress[%]: 0.00 : PID-584932, L2A_ProcessTile: resolution 60 m already processed, elapsed time[s]: 0.072, total: 0:00:00.127838
Progress[%]: 0.01 : PID-584932, L2A_ProcessTile: processing with resolution 20 m, elapsed time[s]: 0.066, total: 0:00:00.193982
Progress[%]: 0.01 : PID-584932, L2A_ProcessTile: start of pre processing, elapsed time[s]: 0.000, total: 0:00:00.194337
Progress[%]: 0.01 : PID-584932, L2A_Tables: start import, elapsed time[s]: 0.075, total: 0:00:00.268937
Progress[%]: 0.21 : PID-584932, L2A_Tables: band B01 imported, elapsed time[s]: 5.123, total: 0:00:05.391898
Progress[%]: 0.77 : PID-584932, L2A_Tables: band B02 imported, elapsed time[s]: 14.292, total: 0:00:19.683881
Progress[%]: 1.31 : PID-584932, L2A_Tables: band B03 imported, elapsed time[s]: 13.838, total: 0:00:33.521586
Progress[%]: 1.86 : PID-584932, L2A_Tables: band B04 imported, elapsed time[s]: 13.886, total: 0:00:47.407161
Progress[%]: 2.00 : PID-584932, L2A_Tables: band B05 imported, elapsed time[s]: 3.582, total: 0:00:50.988904
Progress[%]: 2.14 : PID-584932, L2A_Tables: band B06 imported, elapsed time[s]: 3.580, total: 0:00:54.569269
Progress[%]: 2.28 : PID-584932, L2A_Tables: band B07 imported, elapsed time[s]: 3.594, total: 0:00:58.163352
Progress[%]: 2.42 : PID-584932, L2A_Tables: band B8A imported, elapsed time[s]: 3.652, total: 0:01:01.815207
Progress[%]: 2.61 : PID-584932, L2A_Tables: band B09 imported, elapsed time[s]: 4.706, total: 0:01:06.520779
Progress[%]: 2.79 : PID-584932, L2A_Tables: band B10 imported, elapsed time[s]: 4.630, total: 0:01:11.150321
Progress[%]: 2.92 : PID-584932, L2A_Tables: band B11 imported, elapsed time[s]: 3.411, total: 0:01:14.561312
Progress[%]: 3.06 : PID-584932, L2A_Tables: band B12 imported, elapsed time[s]: 3.491, total: 0:01:18.052093
Progress[%]: 3.06 : PID-584932, L2A_ProcessTile: start of Scene Classification, elapsed time[s]: 0.005, total: 0:01:18.056874
Progress[%]: 3.09 : PID-584932, Pre process   , elapsed time[s]: 0.724, total: 0:01:18.781075
Progress[%]: 3.25 : PID-584932, L2A_SC init   , elapsed time[s]: 4.092, total: 0:01:22.872596
Progress[%]: 3.29 : PID-584932, L2A_CSND_1_1  , elapsed time[s]: 1.195, total: 0:01:24.067808
Progress[%]: 3.35 : PID-584932, L2A_CSND_1_2  , elapsed time[s]: 1.388, total: 0:01:25.455837
Progress[%]: 3.43 : PID-584932, L2A_CSND_3    , elapsed time[s]: 1.957, total: 0:01:27.412949
Progress[%]: 3.50 : PID-584932, L2A_CSND_5_1  , elapsed time[s]: 1.773, total: 0:01:29.185471
Progress[%]: 3.61 : PID-584932, L2A_CSND_5_2  , elapsed time[s]: 2.835, total: 0:01:32.020933
Progress[%]: 3.69 : PID-584932, L2A_CSND_6    , elapsed time[s]: 2.027, total: 0:01:34.047887
Progress[%]: 3.76 : PID-584932, L2A_CSND_6_2  , elapsed time[s]: 1.774, total: 0:01:35.822104
Progress[%]: 3.80 : PID-584932, L2A_CSND_7    , elapsed time[s]: 1.203, total: 0:01:37.024862
Progress[%]: 5.46 : PID-584932, L2A_SHD       , elapsed time[s]: 42.367, total: 0:02:19.392339
Progress[%]: 5.54 : PID-584932, DV recovery   , elapsed time[s]: 1.839, total: 0:02:21.231489
Progress[%]: 5.61 : PID-584932, WP recovery   , elapsed time[s]: 1.798, total: 0:02:23.029070
Progress[%]: 5.61 : PID-584932, WP recovery with CCI Water Bodies at 150m  , elapsed time[s]: 0.002, total: 0:02:23.030751
Progress[%]: 5.69 : PID-584932, Snow recovery , elapsed time[s]: 2.031, total: 0:02:25.061432
Progress[%]: 5.72 : PID-584932, Soil recovery , elapsed time[s]: 0.852, total: 0:02:25.913427
Progress[%]: 5.72 : PID-584932, Land recovery with B10, B09 and B8A , elapsed time[s]: 0.002, total: 0:02:25.915263
Progress[%]: 5.72 : PID-584932, Cirrus recovery with B10 , elapsed time[s]: 0.003, total: 0:02:25.918128
Progress[%]: 5.72 : PID-584932, Urban and Bare pixel recovery with CCI Land Cover Map at 300 m , elapsed time[s]: 0.002, total: 0:02:25.920216
Progress[%]: 5.84 : PID-584932, Post process  , elapsed time[s]: 2.993, total: 0:02:28.913608
Progress[%]: 5.84 : PID-584932, L2A_ProcessTile: start of Atmospheric Correction, elapsed time[s]: 0.001, total: 0:02:28.914246
Progress[%]: 5.93 : PID-584932, L2A_AtmCorr: end of calculation terrain maps, elapsed time[s]: 2.420, total: 0:02:31.334680
Progress[%]: 5.93 : PID-584932, L2A_AtmCorr: start of AOT retrieval at 550nm, elapsed time[s]: 0.004, total: 0:02:31.338184
Progress[%]: 6.16 : PID-584932, L2A_AtmCorr: end of internal classification, elapsed time[s]: 5.817, total: 0:02:37.154706
Progress[%]: 6.18 : PID-584932, L2A_AtmCorr: end of interpolation LUTs, elapsed time[s]: 0.522, total: 0:02:37.677020
Progress[%]: 6.49 : PID-584932, L2A_AtmCorr: end retrieving reference pixels for dark areas, elapsed time[s]: 7.841, total: 0:02:45.518323
Progress[%]: 8.17 : PID-584932, L2A_AtmCorr: end of check for negative reflectance pixels, elapsed time[s]: 42.883, total: 0:03:28.401425
Progress[%]: 8.28 : PID-584932, L2A_AtmCorr: the rescaling of path radiance in blue band has been disabled by configuration, elapsed time[s]: 2.684, total: 0:03:31.085580
Progress[%]: 10.05 : PID-584932, L2A_AtmCorr: end of visibility index calculation, elapsed time[s]: 45.343, total: 0:04:16.428644
Progress[%]: 10.05 : PID-584932, L2A_AtmCorr: end of AOT retrieval at 550nm, elapsed time[s]: 0.000, total: 0:04:16.429109
Progress[%]: 10.05 : PID-584932, L2A_AtmCorr: start of water vapour retrieval, elapsed time[s]: 0.003, total: 0:04:16.431933
Progress[%]: 10.11 : PID-584932, L2A_AtmCorr: end of water vapour retrieval preparation, elapsed time[s]: 1.340, total: 0:04:17.772260
Progress[%]: 14.20 : PID-584932, L2A_AtmCorr: end of water vapour retrieval, elapsed time[s]: 104.328, total: 0:06:02.100277
Progress[%]: 14.20 : PID-584932, L2A_AtmCorr: preparation of surface reflectance retrieval, elapsed time[s]: 0.000, total: 0:06:02.100686
Progress[%]: 14.37 : PID-584932, L2A_AtmCorr: end of surface reflectance retrieval preparation, elapsed time[s]: 4.406, total: 0:06:06.506708
Progress[%]: 18.99 : PID-584932, L2A_AtmCorr: end of surface reflectance retrieval, elapsed time[s]: 117.801, total: 0:08:04.307823
Progress[%]: 20.87 : PID-584932, L2A_AtmCorr: end of rho retrieval step 2, elapsed time[s]: 47.952, total: 0:08:52.259713
Progress[%]: 20.87 : PID-584932, L2A_ProcessTile: start of post processing, elapsed time[s]: 0.030, total: 0:08:52.289366
Progress[%]: 20.87 : PID-584932, L2A_Tables: start export, elapsed time[s]: 0.001, total: 0:08:52.289883
Progress[%]: 21.08 : PID-584932, L2A_Tables: band B02 exported, elapsed time[s]: 5.336, total: 0:08:57.625820
Progress[%]: 21.28 : PID-584932, L2A_Tables: band B03 exported, elapsed time[s]: 5.005, total: 0:09:02.631015
Progress[%]: 21.47 : PID-584932, L2A_Tables: band B04 exported, elapsed time[s]: 4.964, total: 0:09:07.594850
Progress[%]: 21.66 : PID-584932, L2A_Tables: band B05 exported, elapsed time[s]: 4.876, total: 0:09:12.471157
Progress[%]: 21.86 : PID-584932, L2A_Tables: band B06 exported, elapsed time[s]: 5.128, total: 0:09:17.599377
Progress[%]: 22.09 : PID-584932, L2A_Tables: band B07 exported, elapsed time[s]: 5.741, total: 0:09:23.339918
Progress[%]: 22.35 : PID-584932, L2A_Tables: band B8A exported, elapsed time[s]: 6.740, total: 0:09:30.079919
Progress[%]: 22.61 : PID-584932, L2A_Tables: band B11 exported, elapsed time[s]: 6.586, total: 0:09:36.665453
Progress[%]: 22.85 : PID-584932, L2A_Tables: band B12 exported, elapsed time[s]: 5.987, total: 0:09:42.652202
Progress[%]: 22.91 : PID-584932, L2A_Tables: band SCL exported, elapsed time[s]: 1.485, total: 0:09:44.137180
Progress[%]: 22.96 : PID-584932, L2A_Tables: band SNW exported, elapsed time[s]: 1.352, total: 0:09:45.489192
Progress[%]: 23.02 : PID-584932, L2A_Tables: band CLD exported, elapsed time[s]: 1.455, total: 0:09:46.944439
Progress[%]: 23.07 : PID-584932, L2A_Tables: band AOT exported, elapsed time[s]: 1.498, total: 0:09:48.442887
Progress[%]: 23.14 : PID-584932, L2A_Tables: band WVP exported, elapsed time[s]: 1.631, total: 0:09:50.073487
Progress[%]: 23.19 : PID-584932, L2A_Tables: band VIS exported, elapsed time[s]: 1.216, total: 0:09:51.289428
Process L2A_ProcessTile-1:
Traceback (most recent call last):
  File "/home/jn/.sen2r/sen2cor/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jn/.sen2r/sen2cor/lib/python2.7/site-packages/sen2cor/L2A_ProcessTile.py", line 124, in run
    if not self.process_20():
  File "/home/jn/.sen2r/sen2cor/lib/python2.7/site-packages/sen2cor/L2A_ProcessTile.py", line 158, in process_20
    return self.process()
  File "/home/jn/.sen2r/sen2cor/lib/python2.7/site-packages/sen2cor/L2A_ProcessTile.py", line 229, in process
    if self.postprocess() == False:
  File "/home/jn/.sen2r/sen2cor/lib/python2.7/site-packages/sen2cor/L2A_ProcessTile.py", line 311, in postprocess
    if not self.tables.exportBandList():
  File "/home/jn/.sen2r/sen2cor/lib/python2.7/site-packages/sen2cor/L2A_Tables.py", line 2307, in exportBandList
    fn = os.path.basename(self._L2A_Tile_PVI_File)
AttributeError: 'L2A_Tables' object has no attribute '_L2A_Tile_PVI_File'
Syntax error in metadata, see report file for details.
[ERROR]  L2A_XmlParse: 120   Schema file: S2-PDGS-TAS-DI-PSD-V14.2_Schema/S2_User_Product_Level-2A_Metadata.xsd
[ERROR]  L2A_XmlParse: 120   Schema file: S2-PDGS-TAS-DI-PSD-V14.2_Schema/S2_User_Product_Level-2A_Metadata.xsd
[ERROR]  L2A_XmlParse: 121   Details: Element 'L2A_GIPP_List': Missing child element(s). Expected is ( GIPP_FILENAME ).
[ERROR]  L2A_XmlParse: 121   Details: Element 'L2A_GIPP_List': Missing child element(s). Expected is ( GIPP_FILENAME ).
Parsing error:
Schema file: S2-PDGS-TAS-DI-PSD-V14.2_Schema/S2_User_Product_Level-2A_Metadata.xsd
Details: Element 'L2A_GIPP_List': Missing child element(s). Expected is ( GIPP_FILENAME ).
Progress[%]: 100.00 : Application terminated successfully.
```

**Comment by ranghetti** [comment]
This is an error related to Sen2Cor (which is not part of sen2r), so I cannot give assistance for it. I could suggest trying with another version (2.8.0 if you installed 2.5.5, or vice versa).

**Comment by Nowosad** [comment]
I will try that. Thank you @ranghetti
